"""Initial schema

Revision ID: 40f61c5e796d
Revises: 
Create Date: 2026-06-13 22:01:42.379330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f61c5e796d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misconception_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconception_master_code'), 'misconception_master', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'PARENT', name='userrole'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('parent_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('board', sa.String(), nullable=True),
    sa.Column('preferredLanguage', sa.String(), nullable=True),
    sa.Column('learningPace', sa.Enum('SLOW', 'MEDIUM', 'FAST', name='learningpace'), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('teacher_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teacherId', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('strictness', sa.String(), nullable=True),
    sa.Column('dueDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacherId'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.Column('studentId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['parent_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_misconceptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('studentId', sa.String(), nullable=True),
    sa.Column('misconceptionId', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('lastSeenAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('masteryScore', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['misconceptionId'], ['misconception_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_topic_mastery',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('studentId', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('studentId', sa.String(), nullable=True),
    sa.Column('assignmentId', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('inputType', sa.Enum('TEXT', 'IMAGE', 'PDF', name='inputtype'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='sessionstatus'), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignmentId'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studentId'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teacherId', sa.String(), nullable=True),
    sa.Column('assignmentId', sa.String(), nullable=True),
    sa.Column('strictness', sa.Enum('HINT_ONLY', 'GUIDED', 'REVIEW', name='strictnesslevel'), nullable=True),
    sa.Column('allowPrerequisites', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assignmentId'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacherId'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('IMAGE', 'PDF', name='attachmenttype'), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sessionId'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_diagnoses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=True),
    sa.Column('understandingLevel', sa.Enum('NONE', 'PARTIAL', 'GOOD', name='understandinglevel'), nullable=True),
    sa.Column('misconceptionType', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sessionId'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('weakness', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sessionId'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'AI', name='roletype'), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sessionId'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writes',
    sa.Column('thread_id', sa.TEXT(), nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), nullable=False),
    sa.Column('task_id', sa.TEXT(), nullable=False),
    sa.Column('idx', sa.INTEGER(), nullable=False),
    sa.Column('channel', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('value', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('checkpoint', sa.BLOB(), nullable=True),
    sa.Column('metadata', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    op.drop_table('session_messages')
    op.drop_table('session_insights')
    op.drop_table('session_diagnoses')
    op.drop_table('attachments')
    op.drop_table('teacher_settings')
    op.drop_table('sessions')
    op.drop_table('student_topic_mastery')
    op.drop_table('student_misconceptions')
    op.drop_table('parent_students')
    op.drop_table('assignments')
    op.drop_table('teacher_profiles')
    op.drop_table('student_profiles')
    op.drop_table('parent_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_misconception_master_code'), table_name='misconception_master')
    op.drop_table('misconception_master')
    # ### end Alembic commands ###
